import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Fastify from 'fastify';
import fastifyStatic from '@fastify/static';
import { parseStringPromise } from 'xml2js';
import { GoogleGenerativeAI } from '@google/generative-ai';

import { getPollData, incrementVote, getVoteEvents, seedVoteEvents, getCachedExplanation, setCachedExplanation } from './db.js';
import { pingSearchEngines, getIndexNowKey } from './indexing.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper to load Gemini API key from api-keys.env or environment variables
function getApiKey() {
  if (process.env.GEMINI_API_KEY) return process.env.GEMINI_API_KEY;
  if (process.env.GOOGLE_PROFITHELM_FREE_KEY) return process.env.GOOGLE_PROFITHELM_FREE_KEY;

  try {
    const envPath = '/home/ubuntuadmin/projects/api-keys.env';
    if (fs.existsSync(envPath)) {
      const content = fs.readFileSync(envPath, 'utf8');
      const match = content.match(/GOOGLE_PROFITHELM_FREE_KEY=([^\s]+)/);
      if (match && match[1]) {
        return match[1].trim();
      }
    }
  } catch (err) {
    console.error('Error reading api-keys.env:', err);
  }
  return null;
}

function titleToSlug(title) {
  return title.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

const apiKey = getApiKey();
if (!apiKey) {
  console.warn('WARNING: No Google Gemini API key found. AI features will fail.');
}

const genAI = apiKey ? new GoogleGenerativeAI(apiKey) : null;

const fastify = Fastify({ logger: true });

// GET / - Serves the main page with the first trend preloaded for instant hydration
fastify.get('/', async (request, reply) => {
  try {
    if (latestTrends.length === 0) {
      if (process.env.NODE_ENV === 'test') {
        latestTrends = [
          {
            id: 1,
            title: "Google Gemini",
            traffic: "100K+",
            description: "The latest AI models from Google.",
            source: "google",
            news: {
              headline: "Google announces Gemini 3.5",
              snippet: "Gemini 3.5 is now live with advanced reasoning capabilities.",
              url: "https://blog.google/gemini-3.5",
              source: "Google Blog",
              ogImage: "https://blog.google/static/images/gemini-hero.png",
              favicon: "https://blog.google/favicon.ico"
            }
          },
          {
            id: 2,
            title: "Fastify framework",
            traffic: "20K+",
            description: "High performance web framework for Node.js.",
            source: "google",
            news: {
              headline: "Fastify v5 released",
              snippet: "Fastify v5 introduces improved plugin loading and security features.",
              url: "https://fastify.io/v5-release",
              source: "Fastify Blog",
              ogImage: null,
              favicon: "https://www.google.com/s2/favicons?domain=fastify.io&sz=32"
            }
          }
        ];
      } else {
        await updateTrendsCache();
      }
    }
  } catch (err) {
    console.error('Failed to populate trends cache for home page:', err);
  }

  const trendName = latestTrends.length > 0 ? latestTrends[0].title : "Google Gemini";
  const slug = titleToSlug(trendName);

  let explanation;
  try {
    explanation = await getTrendExplanation(trendName, '', '');
  } catch (err) {
    explanation = {
      hook: `Why is everyone talking about ${trendName}?`,
      whatIsIt: `Trending search topic: ${trendName}.`,
      whyIsItViral: [`High volume search interest on Google Trends.`],
      takeaway: `Keep an eye on this trend as it develops.`,
      polls: await getPollData(trendName)
    };
  }

  try {
    const indexPath = path.join(__dirname, 'public', 'index.html');
    let html = fs.readFileSync(indexPath, 'utf-8');

    const jsonLd = {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "headline": `Why is ${trendName} Trending? Genius vs Overrated Explanation`,
      "description": explanation.hook,
      "articleBody": `${explanation.whatIsIt} Takeaway: ${explanation.takeaway}`,
      "author": {
        "@type": "Organization",
        "name": "TrendJacker"
      }
    };

    const seoMeta = `
  <!-- SEO & GEO Meta Tags dynamically generated by TrendJacker Agent -->
  <title>Why is ${trendName} Trending? | TrendJacker</title>
  <meta name="description" content="${explanation.hook}">
  <meta property="og:title" content="Why is ${trendName} Trending? | TrendJacker">
  <meta property="og:description" content="${explanation.hook}">
  <meta property="og:type" content="article">
  <meta property="og:url" content="https://viraljacker.com/t/${slug}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Why is ${trendName} Trending? | TrendJacker">
  <meta name="twitter:description" content="${explanation.hook}">
  <link rel="alternate" type="text/markdown" href="/llms.txt">
  
  <script type="application/ld+json">
    ${JSON.stringify(jsonLd, null, 2)}
  </script>
  
  <!-- Preloaded Data block for client hydration -->
  <script id="preloaded-trend-data" type="application/json">
    ${JSON.stringify({ trend: trendName, slug, explanation })}
  </script>
    `;

    html = html.replace(/<title>.*?<\/title>/, '');
    html = html.replace(/<meta\s+name="description"\s+content=".*?">/, '');
    html = html.replace('</head>', `${seoMeta}\n</head>`);

    reply.type('text/html').send(html);
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send({ error: 'Failed to render home page.' });
  }
});

// Register static files
fastify.register(fastifyStatic, {
  root: path.join(__dirname, 'public'),
  prefix: '/',
});

// Database initialized via db.js module

// Locations for simulated votes
const LOCATIONS = [
  { city: 'Tokyo', country: 'Japan', flag: '🇯🇵' },
  { city: 'Paris', country: 'France', flag: '🇫🇷' },
  { city: 'New York', country: 'United States', flag: '🇺🇸' },
  { city: 'London', country: 'United Kingdom', flag: '🇬🇧' },
  { city: 'Sydney', country: 'Australia', flag: '🇦🇺' },
  { city: 'Berlin', country: 'Germany', flag: '🇩🇪' },
  { city: 'Toronto', country: 'Canada', flag: '🇨🇦' },
  { city: 'Mumbai', country: 'India', flag: '🇮🇳' },
  { city: 'São Paulo', country: 'Brazil', flag: '🇧🇷' },
  { city: 'Cape Town', country: 'South Africa', flag: '🇿🇦' },
  { city: 'Singapore', country: 'Singapore', flag: '🇸🇬' },
  { city: 'Seoul', country: 'South Korea', flag: '🇰🇷' },
  { city: 'Mexico City', country: 'Mexico', flag: '🇲🇽' },
  { city: 'Dubai', country: 'United Arab Emirates', flag: '🇦🇪' },
  { city: 'Stockholm', country: 'Sweden', flag: '🇸🇪' }
];

const DEFAULT_TRENDS = [
  { title: "AI Agent", traffic: "100K+", description: "Autonomous software agents taking over tasks." },
  { title: "Apple Vision Pro", traffic: "50K+", description: "Spatial computing and virtual reality headset." },
  { title: "ChatGPT", traffic: "200K+", description: "Conversational language model by OpenAI." },
  { title: "Claude 3.5", traffic: "100K+", description: "Anthropic's latest state-of-the-art model." },
  { title: "Remote Work", traffic: "20K+", description: "The shifting landscape of work environments." },
  { title: "Electric Vehicles", traffic: "50K+", description: "Transition from internal combustion engines." },
  { title: "Self-Driving Cars", traffic: "30K+", description: "Autonomous vehicle technology updates." },
  { title: "Quantum Computing", traffic: "10K+", description: "Computing using quantum-mechanical phenomena." },
  { title: "Fusion Energy", traffic: "10K+", description: "Clean power generation technology." },
  { title: "Web3", traffic: "20K+", description: "Decentralized web technologies and blockchain." }
];

let latestTrends = [];
const pingedSlugs = new Set();
let recentActivityLog = [];
const MAX_ACTIVITY_LOG_SIZE = 15;

function logActivity(activity) {
  recentActivityLog.unshift(activity);
  if (recentActivityLog.length > MAX_ACTIVITY_LOG_SIZE) {
    recentActivityLog = recentActivityLog.slice(0, MAX_ACTIVITY_LOG_SIZE);
  }
}

function seedRecentActivityLog() {
  const trendsList = latestTrends.length > 0 ? latestTrends : DEFAULT_TRENDS;
  recentActivityLog = [];
  const now = Date.now();
  for (let i = 0; i < 10; i++) {
    const randomTrend = trendsList[Math.floor(Math.random() * trendsList.length)];
    const location = LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)];
    const vote = i % 2 === 0 ? 'genius' : 'overrated';
    recentActivityLog.push({
      trend: randomTrend.title,
      vote,
      location,
      clientId: `mock-client-${i}`,
      timestamp: now - i * 90000
    });
  }
  console.log(`Seeded recentActivityLog with ${recentActivityLog.length} items.`);
}

// Scraper helper to fetch metadata
async function fetchMetadata(url) {
  if (!url) return { ogImage: null, favicon: null };
  try {
    const parsedUrl = new URL(url);
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 2000);

    const response = await fetch(url, {
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
      }
    });
    clearTimeout(timeoutId);

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    const html = await response.text();
    
    // Parse ogImage
    let ogImage = null;
    const ogImageMatch = html.match(/<meta[^>]*?(?:property|name)=["']og:image["'][^>]*?content=["']([^"']+)["']/i) ||
                         html.match(/<meta[^>]*?content=["']([^"']+)["'][^>]*?(?:property|name)=["']og:image["']/i);
    if (ogImageMatch) {
      ogImage = ogImageMatch[1];
    } else {
      const twitterImageMatch = html.match(/<meta[^>]*?(?:property|name)=["']twitter:image["'][^>]*?content=["']([^"']+)["']/i) ||
                                html.match(/<meta[^>]*?content=["']([^"']+)["'][^>]*?(?:property|name)=["']twitter:image["']/i);
      if (twitterImageMatch) {
        ogImage = twitterImageMatch[1];
      }
    }

    if (ogImage && !ogImage.startsWith('http')) {
      ogImage = new URL(ogImage, parsedUrl.origin).href;
    }

    // Parse favicon
    let favicon = null;
    const faviconMatch = html.match(/<link[^>]*?rel=["'](?:shortcut\s+)?icon["'][^>]*?href=["']([^"']+)["']/i) ||
                         html.match(/<link[^>]*?href=["']([^"']+)["'][^>]*?rel=["'](?:shortcut\s+)?icon["']/i);
    if (faviconMatch) {
      favicon = faviconMatch[1];
    }

    if (favicon && !favicon.startsWith('http')) {
      favicon = new URL(favicon, parsedUrl.origin).href;
    }

    if (!favicon) {
      favicon = `https://www.google.com/s2/favicons?domain=${parsedUrl.hostname}&sz=32`;
    }

    return { ogImage, favicon };
  } catch (err) {
    let fallbackFavicon = null;
    try {
      const parsedUrl = new URL(url);
      fallbackFavicon = `https://www.google.com/s2/favicons?domain=${parsedUrl.hostname}&sz=32`;
    } catch (_) {}
    return { ogImage: null, favicon: fallbackFavicon };
  }
}

// Helper to fetch trends and populate cache
async function updateTrendsCache() {
  if (process.env.NODE_ENV === 'test') {
    latestTrends = [
      {
        id: 1,
        title: "Google Gemini",
        traffic: "100K+",
        description: "The latest AI models from Google.",
        source: "google",
        news: {
          headline: "Google announces Gemini 3.5",
          snippet: "Gemini 3.5 is now live with advanced reasoning capabilities.",
          url: "https://blog.google/gemini-3.5",
          source: "Google Blog",
          ogImage: "https://blog.google/static/images/gemini-hero.png",
          favicon: "https://blog.google/favicon.ico"
        }
      },
      {
        id: 2,
        title: "Fastify framework",
        traffic: "20K+",
        description: "High performance web framework for Node.js.",
        source: "google",
        news: {
          headline: "Fastify v5 released",
          snippet: "Fastify v5 introduces improved plugin loading and security features.",
          url: "https://fastify.io/v5-release",
          source: "Fastify Blog",
          ogImage: null,
          favicon: "https://www.google.com/s2/favicons?domain=fastify.io&sz=32"
        }
      }
    ];
    return;
  }

  let googleTrends = [];
  let redditTrends = [];

  // 1. Fetch Google Trends RSS
  try {
    const googleResponse = await fetch('https://trends.google.com/trending/rss?geo=US');
    if (googleResponse.ok) {
      const xmlText = await googleResponse.text();
      const result = await parseStringPromise(xmlText);
      const items = result.rss.channel[0].item || [];
      googleTrends = items.map((item, index) => {
        const traffic = item['ht:approx_traffic'] ? item['ht:approx_traffic'][0] : 'N/A';
        const newsItem = item['ht:news_item'] ? item['ht:news_item'][0] : null;
        
        const snippet = newsItem && newsItem['ht:news_item_snippet'] ? newsItem['ht:news_item_snippet'][0] : '';
        const headline = newsItem && newsItem['ht:news_item_title'] ? newsItem['ht:news_item_title'][0] : '';
        const newsUrl = newsItem && newsItem['ht:news_item_url'] ? newsItem['ht:news_item_url'][0] : '';
        const newsSource = newsItem && newsItem['ht:news_item_source'] ? newsItem['ht:news_item_source'][0] : '';

        return {
          id: `google-${index}`,
          title: item.title[0],
          traffic,
          description: item.description ? item.description[0] : '',
          source: 'google',
          news: {
            headline,
            snippet,
            url: newsUrl,
            source: newsSource
          }
        };
      });
    } else {
      console.error(`Failed to fetch Google Trends RSS: ${googleResponse.status}`);
    }
  } catch (err) {
    console.error('Failed to fetch Google Trends RSS:', err.message);
  }

  // 2. Fetch Reddit Popular RSS
  try {
    const redditResponse = await fetch('https://www.reddit.com/r/popular.rss', {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Cache-Control': 'max-age=0'
      }
    });

    if (redditResponse.ok) {
      const xmlText = await redditResponse.text();
      const result = await parseStringPromise(xmlText);
      const entries = (result.feed && result.feed.entry) || [];
      redditTrends = entries.map((entry, index) => {
        const title = entry.title ? entry.title[0] : 'Reddit Thread';
        const link = (entry.link && entry.link[0] && entry.link[0].$) ? entry.link[0].$.href : '';
        const category = (entry.category && entry.category[0] && entry.category[0].$) 
          ? (entry.category[0].$.label || entry.category[0].$.term || 'r/popular')
          : 'r/popular';

        return {
          id: `reddit-${index}`,
          title: title.length > 60 ? title.substring(0, 60) + '...' : title,
          traffic: 'Reddit Spike',
          description: `Hot post on ${category}`,
          source: 'reddit',
          news: {
            headline: title,
            snippet: `Early interest spike on Reddit in the ${category} community.`,
            url: link,
            source: category
          }
        };
      });
    } else {
      console.error(`Failed to fetch Reddit RSS: ${redditResponse.status}`);
    }
  } catch (err) {
    console.error('Failed to fetch Reddit RSS:', err.message);
  }

  // 3. Merge and Deduplicate by Title Slug
  const merged = [];
  const seenSlugs = new Set();

  // Add Google trends first
  for (const item of googleTrends) {
    const slug = titleToSlug(item.title);
    if (!seenSlugs.has(slug)) {
      seenSlugs.add(slug);
      merged.push(item);
    }
  }

  // Add Reddit spikes next if not already seen
  for (const item of redditTrends) {
    const slug = titleToSlug(item.title);
    if (!seenSlugs.has(slug)) {
      seenSlugs.add(slug);
      merged.push(item);
    }
  }

  // If both failed, use default trends
  if (merged.length === 0) {
    console.warn('Both Google and Reddit RSS failed. Using fallbacks.');
  } else {
    if (merged.length > 0) {
      const metadataPromises = merged.map(async (item) => {
        if (item.news && item.news.url) {
          const meta = await fetchMetadata(item.news.url);
          item.news.ogImage = meta.ogImage;
          item.news.favicon = meta.favicon;
        } else if (item.news) {
          item.news.ogImage = null;
          item.news.favicon = null;
        }
      });
      await Promise.all(metadataPromises);
    }
    latestTrends = merged;
    console.log(`Successfully cached ${latestTrends.length} blended trends.`);
  }

  // Trigger search engine indexing pings for newly discovered trends
  const newSlugs = [];
  for (const trend of latestTrends) {
    const slug = titleToSlug(trend.title);
    if (!pingedSlugs.has(slug)) {
      pingedSlugs.add(slug);
      newSlugs.push(slug);
    }
  }
  if (newSlugs.length > 0) {
    pingSearchEngines(newSlugs).catch(err => {
      console.error('Failed to trigger search engine pings:', err);
    });
  }
}

// GET /api/trends - Fetches and parses Google Trends RSS feed
fastify.get('/api/trends', async (request, reply) => {
  try {
    if (latestTrends.length === 0) {
      await updateTrendsCache();
    }
    return latestTrends.slice(0, 15);
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send({ error: 'Failed to fetch trending topics.' });
  }
});

// GET /<INDEXNOW_KEY>.txt - Serves verification key for IndexNow API ownership checks
const indexNowKey = getIndexNowKey();
fastify.get(`/${indexNowKey}.txt`, async (request, reply) => {
  reply.header('Content-Type', 'text/plain');
  return indexNowKey;
});

// Server-Sent Events Clients for live sentiment feed
const sseClients = new Set();
let globalSimulationInterval = null;

function broadcastSSE(data) {
  const message = `data: ${JSON.stringify(data)}\n\n`;
  for (const client of sseClients) {
    try {
      client.write(message);
    } catch (err) {
      // Client disconnected
    }
  }
}

function startGlobalSimulation() {
  if (globalSimulationInterval) return;
  console.log('Starting global sentiment simulation timer.');
  globalSimulationInterval = setInterval(async () => {
    if (sseClients.size === 0) {
      stopGlobalSimulation();
      return;
    }

    const trendsList = latestTrends.length > 0 ? latestTrends : DEFAULT_TRENDS;
    const randomTrend = trendsList[Math.floor(Math.random() * trendsList.length)];
    const vote = Math.random() > 0.55 ? 'genius' : 'overrated';
    const location = LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)];

    let updatedPolls = null;
    try {
      updatedPolls = await incrementVote(randomTrend.title, vote, location);
    } catch (err) {
      console.error(`Failed to increment simulated vote for "${randomTrend.title}":`, err.message);
    }

    const timestamp = new Date().toISOString();
    const activity = {
      trend: randomTrend.title,
      vote,
      location,
      clientId: 'simulated-client',
      timestamp
    };

    logActivity(activity);

    broadcastSSE({
      ...activity,
      updatedPolls
    });
  }, 4000); // Simulated vote broadcasted every 4 seconds
}

function stopGlobalSimulation() {
  if (globalSimulationInterval) {
    clearInterval(globalSimulationInterval);
    globalSimulationInterval = null;
    console.log('Stopped global sentiment simulation (no clients connected).');
  }
}

// GET /api/sentiment-stream - SSE endpoint for global activity feed
fastify.get('/api/sentiment-stream', (request, reply) => {
  reply.raw.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'Access-Control-Allow-Origin': '*'
  });

  reply.raw.write(`event: hydration\ndata: ${JSON.stringify(recentActivityLog)}\n\n`);
  reply.raw.write('retry: 5000\n\n');
  sseClients.add(reply.raw);
  startGlobalSimulation();

  request.raw.on('close', () => {
    sseClients.delete(reply.raw);
    if (sseClients.size === 0) {
      stopGlobalSimulation();
    }
  });
});

// Helper to get explanation from Gemini
async function getTrendExplanation(trend, headline = '', snippet = '') {
  // Check the cache first
  const cached = await getCachedExplanation(trend);
  if (cached) {
    cached.polls = await getPollData(trend);
    return cached;
  }

  let explanation;
  if (process.env.NODE_ENV === 'test') {
    explanation = {
      hook: 'Gemini is capturing developer mindshare with low latency and long context.',
      whatIsIt: 'Google Gemini is a suite of multimodal generative AI models.',
      whyIsItViral: ['Long context window', 'Low latency API', 'Reasoning capability'],
      takeaway: 'Expect Gemini to power next-gen agentic workflows.'
    };
  } else {
    if (!genAI) {
      throw new Error('Gemini API not configured.');
    }

    const model = genAI.getGenerativeModel({
      model: 'gemini-3.5-flash',
      generationConfig: { 
        thinkingConfig: { thinkingLevel: 'LOW' },
        responseMimeType: 'application/json',
        responseSchema: {
          type: "OBJECT",
          properties: {
            hook: { type: "STRING" },
            whatIsIt: { type: "STRING" },
            whyIsItViral: {
              type: "ARRAY",
              items: { type: "STRING" }
            },
            takeaway: { type: "STRING" }
          },
          required: ["hook", "whatIsIt", "whyIsItViral", "takeaway"]
        },
        thinkingConfig: { thinkingLevel: 'LOW' }
      }
    });

    const prompt = `You are a viral trend analyst. Explain why the topic "${trend}" is trending.
Here is the context headline: "${headline || ''}".
Here is the context snippet: "${snippet || ''}".`;

    const result = await model.generateContent(prompt);
    const textResponse = result.response.text();
    
    let cleanedText = textResponse.trim();
    if (cleanedText.startsWith('```')) {
      cleanedText = cleanedText.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/, '').trim();
    }
    
    explanation = JSON.parse(cleanedText);
  }

  // Write explanation to cache
  await setCachedExplanation(trend, explanation);

  // Retrieve live poll statistics
  explanation.polls = await getPollData(trend);
  return explanation;
}

// POST /api/explain - Explains a trend using Gemini
fastify.post('/api/explain', async (request, reply) => {
  const { trend, snippet, headline } = request.body || {};
  if (!trend) {
    return reply.status(400).send({ error: 'Trend name is required.' });
  }

  try {
    const explanation = await getTrendExplanation(trend, headline, snippet);
    return explanation;
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send({ error: 'Failed to generate trend explanation.' });
  }
});




// GET /t/:slug - Dynamically renders a trend explainer page with SEO/GEO metadata
fastify.get('/t/:slug', async (request, reply) => {
  let { slug } = request.params;
  if (!slug) {
    return reply.redirect('/');
  }

  const isMarkdown = slug.endsWith('.md');
  if (isMarkdown) {
    slug = slug.slice(0, -3);
  }

  // Determine standard name from slug
  let trendName = '';
  let headline = '';
  let snippet = '';
  let isFound = false;

  try {
    if (latestTrends.length === 0) {
      await updateTrendsCache();
    }
    const match = latestTrends.find(item => titleToSlug(item.title) === slug);
    if (match) {
      trendName = match.title;
      const newsItem = match.news || {};
      snippet = newsItem.snippet || '';
      headline = newsItem.headline || '';
      isFound = true;
    } else {
      // Fallback
      const response = await fetch('https://trends.google.com/trending/rss?geo=US');
      if (response.ok) {
        const xmlText = await response.text();
        const result = await parseStringPromise(xmlText);
        const items = result.rss.channel[0].item || [];
        const liveMatch = items.find(item => titleToSlug(item.title[0]) === slug);
        if (liveMatch) {
          trendName = liveMatch.title[0];
          const newsItem = liveMatch['ht:news_item'] ? liveMatch['ht:news_item'][0] : null;
          snippet = newsItem && newsItem['ht:news_item_snippet'] ? newsItem['ht:news_item_snippet'][0] : '';
          headline = newsItem && newsItem['ht:news_item_title'] ? newsItem['ht:news_item_title'][0] : '';
          isFound = true;
        }
      }
    }
  } catch (err) {
    console.error('Error matching slug against live trends:', err.message);
  }

  if (isMarkdown && !isFound) {
    return reply.status(404).send({ error: 'Trend not found' });
  }

  if (!trendName) {
    trendName = slug.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  }

  let explanation;
  try {
    explanation = await getTrendExplanation(trendName, headline, snippet);
  } catch (err) {
    fastify.log.error(err);
    explanation = {
      hook: `Why is everyone talking about ${trendName}?`,
      whatIsIt: `Trending search topic: ${trendName}.`,
      whyIsItViral: [`High volume search interest on Google Trends.`],
      takeaway: `Keep an eye on this trend as it develops.`,
      polls: await getPollData(trendName)
    };
  }

  if (isMarkdown) {
    let md = `# ${trendName}\n\n`;
    md += `Hook: ${explanation.hook || ''}\n\n`;
    md += `Explanation: ${explanation.whatIsIt || ''}\n\n`;
    md += `Why it is viral:\n`;
    if (explanation.whyIsItViral && Array.isArray(explanation.whyIsItViral)) {
      for (const viralReason of explanation.whyIsItViral) {
        md += `- ${viralReason}\n`;
      }
    }
    md += `\n`;
    md += `Takeaway: ${explanation.takeaway || ''}\n\n`;
    md += `Poll Statistics:\n`;
    md += `- Genius: ${explanation.polls?.genius || 0}\n`;
    md += `- Overrated: ${explanation.polls?.overrated || 0}\n`;

    reply.header('Content-Type', 'text/plain');
    return md;
  }

  try {
    const indexPath = path.join(__dirname, 'public', 'index.html');
    let html = fs.readFileSync(indexPath, 'utf-8');

    const jsonLd = {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "headline": `Why is ${trendName} Trending? Genius vs Overrated Explanation`,
      "description": explanation.hook,
      "articleBody": `${explanation.whatIsIt} Takeaway: ${explanation.takeaway}`,
      "author": {
        "@type": "Organization",
        "name": "TrendJacker"
      }
    };

    const seoMeta = `
  <!-- SEO & GEO Meta Tags dynamically generated by TrendJacker Agent -->
  <title>Why is ${trendName} Trending? | TrendJacker</title>
  <meta name="description" content="${explanation.hook}">
  <meta property="og:title" content="Why is ${trendName} Trending? | TrendJacker">
  <meta property="og:description" content="${explanation.hook}">
  <meta property="og:type" content="article">
  <meta property="og:url" content="https://viraljacker.com/t/${slug}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Why is ${trendName} Trending? | TrendJacker">
  <meta name="twitter:description" content="${explanation.hook}">
  <link rel="alternate" type="text/markdown" href="/llms.txt">
  
  <script type="application/ld+json">
    ${JSON.stringify(jsonLd, null, 2)}
  </script>
  
  <!-- Preloaded Data block for client hydration -->
  <script id="preloaded-trend-data" type="application/json">
    ${JSON.stringify({ trend: trendName, slug, explanation })}
  </script>
    `;

    html = html.replace(/<title>.*?<\/title>/, '');
    html = html.replace(/<meta\s+name="description"\s+content=".*?">/, '');
    html = html.replace('</head>', `${seoMeta}\n</head>`);

    reply.type('text/html').send(html);
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send({ error: 'Failed to render trend page.' });
  }
});

// GET /robots.txt - Dynamic robots.txt
fastify.get('/robots.txt', async (request, reply) => {
  reply.header('Content-Type', 'text/plain');
  return `User-agent: *\nAllow: /\nSitemap: https://viraljacker.com/sitemap.xml`;
});

// GET /llms.txt - Dynamic llms.txt sitemap
fastify.get('/llms.txt', async (request, reply) => {
  try {
    if (latestTrends.length === 0) {
      await updateTrendsCache();
    }
    let md = `# TrendJacker\n`;
    md += `> TrendJacker is a dynamic viral trend explainer platform summarizing what is trending and why.\n\n`;
    md += `## Trends\n`;
    for (const trend of latestTrends) {
      const slug = titleToSlug(trend.title);
      const desc = trend.description || 'No description available.';
      md += `- [/t/${slug}.md](/t/${slug}.md) - ${desc}\n`;
    }
    reply.header('Content-Type', 'text/plain');
    return md;
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send('Error generating llms.txt');
  }
});

// GET /llms-full.txt - compiles the full content of all trending topics
fastify.get('/llms-full.txt', async (request, reply) => {
  try {
    if (latestTrends.length === 0) {
      await updateTrendsCache();
    }
    
    let md = `# TrendJacker - Full Content\n\n`;
    
    const trendsExplanations = await Promise.all(
      latestTrends.map(async (trend) => {
        const headline = trend.news?.headline || '';
        const snippet = trend.news?.snippet || '';
        let explanation;
        try {
          explanation = await getTrendExplanation(trend.title, headline, snippet);
        } catch (err) {
          explanation = {
            hook: `Why is everyone talking about ${trend.title}?`,
            whatIsIt: `Trending search topic: ${trend.title}.`,
            whyIsItViral: [`High volume search interest on Google Trends.`],
            takeaway: `Keep an eye on this trend as it develops.`,
            polls: { overrated: 0, genius: 0 }
          };
        }
        return { trend, explanation };
      })
    );
    
    for (const { trend, explanation } of trendsExplanations) {
      md += `## ${trend.title}\n`;
      md += `Snippet: ${trend.news?.snippet || ''}\n`;
      md += `Explanation: ${explanation.whatIsIt || ''}\n`;
      md += `Why it is viral:\n`;
      if (explanation.whyIsItViral && Array.isArray(explanation.whyIsItViral)) {
        for (const viralReason of explanation.whyIsItViral) {
          md += `- ${viralReason}\n`;
        }
      }
      md += `Takeaway: ${explanation.takeaway || ''}\n\n`;
    }
    
    reply.header('Content-Type', 'text/plain');
    return md;
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send('Error generating llms-full.txt');
  }
});

// GET /sitemap.xml - Dynamic sitemap generator
fastify.get('/sitemap.xml', async (request, reply) => {
  try {
    if (latestTrends.length === 0) {
      await updateTrendsCache();
    }
    const slugs = latestTrends.map(item => titleToSlug(item.title));

    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
    xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
    
    // Add homepage
    xml += `  <url>\n`;
    xml += `    <loc>https://viraljacker.com/</loc>\n`;
    xml += `    <changefreq>daily</changefreq>\n`;
    xml += `    <priority>1.0</priority>\n`;
    xml += `  </url>\n`;
    
    // Add trend pages
    for (const slug of slugs) {
      xml += `  <url>\n`;
      xml += `    <loc>https://viraljacker.com/t/${slug}</loc>\n`;
      xml += `    <changefreq>daily</changefreq>\n`;
      xml += `    <priority>0.8</priority>\n`;
      xml += `  </url>\n`;
    }
    
    xml += `</urlset>`;

    reply.type('application/xml').send(xml);
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send('Error generating sitemap');
  }
});

// POST /api/chat - Follow-up Q&A chat using Gemini
fastify.post('/api/chat', async (request, reply) => {
  const { trend, query, history } = request.body || {};
  if (!trend || !query) {
    return reply.status(400).send({ error: 'Trend and query are required.' });
  }

  if (process.env.NODE_ENV === 'test') {
    return { reply: 'This is a mock reply for: ' + query };
  }

  if (!genAI) {
    return reply.status(500).send({ error: 'Gemini API not configured.' });
  }

  try {
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-3.5-flash',
      generationConfig: {
        thinkingConfig: { thinkingLevel: 'LOW' }
      }
    });

    // Format chat history for prompt context
    const historyText = (history || [])
      .map(msg => `${msg.role === 'user' ? 'User' : 'Assistant'}: ${msg.content}`)
      .join('\n');

    const prompt = `You are a sharp, conversational AI trend analyst. The user is asking a follow-up question about the trending topic "${trend}".
Keep your response under 3 sentences, make it engaging, and focus on delivering direct answers.

Conversation history:
${historyText}

User query: ${query}

Response:`;

    const result = await model.generateContent(prompt);
    const replyText = result.response.text();
    return { reply: replyText.trim() };
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send({ error: 'Failed to generate chat response.' });
  }
});

// POST /api/poll - Records a sentiment vote for a trend
fastify.post('/api/poll', async (request, reply) => {
  const { trend, vote, location, clientId } = request.body || {};
  if (!trend || !['overrated', 'genius'].includes(vote)) {
    return reply.status(400).send({ error: 'Valid trend and vote (overrated/genius) are required.' });
  }

  const updatedPolls = await incrementVote(trend, vote, location);

  const timestamp = new Date().toISOString();
  const activity = {
    trend,
    vote,
    location: location || { city: 'Unknown', country: 'Unknown', flag: '📍' },
    clientId: clientId || 'anonymous',
    timestamp
  };

  logActivity(activity);

  broadcastSSE({
    ...activity,
    updatedPolls
  });

  return updatedPolls;
});

// GET /api/poll/history - Retrieves historical sentiment timeline data for a trend
fastify.get('/api/poll/history', async (request, reply) => {
  const { trend } = request.query || {};
  if (!trend || !trend.trim()) {
    return reply.status(400).send({ error: 'Trend query parameter is required.' });
  }

  let events = await getVoteEvents(trend);
  if (!events || events.length === 0) {
    const mockVotes = [];
    const now = Date.now();
    const hours24 = 24 * 60 * 60 * 1000;
    const segmentMs = hours24 / 10;
    for (let i = 0; i < 10; i++) {
      const segmentStart = now - hours24 + i * segmentMs;
      const votesCount = Math.floor(Math.random() * 3) + 1;
      for (let j = 0; j < votesCount; j++) {
        const timestampMs = segmentStart + Math.random() * segmentMs;
        const timestamp = new Date(timestampMs).toISOString();
        const vote = Math.random() < 0.65 ? 'genius' : 'overrated';
        const location = LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)];
        mockVotes.push({ vote, timestamp, location });
      }
    }
    mockVotes.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));
    await seedVoteEvents(trend, mockVotes);
    events = await getVoteEvents(trend);
  }

  const nowMs = events.length > 0
    ? Math.max(...events.map(e => new Date(e.timestamp).getTime()))
    : Date.now();
  const hours24 = 24 * 60 * 60 * 1000;
  const segmentMs = hours24 / 10;
  const startMs = nowMs - hours24;

  const points = [];
  for (let i = 1; i <= 10; i++) {
    const intervalStart = startMs + (i - 1) * segmentMs;
    const intervalEnd = startMs + i * segmentMs;

    const votesInInterval = events.filter(e => {
      const t = new Date(e.timestamp).getTime();
      return t >= intervalStart && t < intervalEnd;
    });
    const velocity = votesInInterval.length;

    const cumulativeVotes = events.filter(e => {
      const t = new Date(e.timestamp).getTime();
      return t < intervalEnd;
    });

    let geniusPercentage = 50;
    if (cumulativeVotes.length > 0) {
      const geniusVotes = cumulativeVotes.filter(e => e.vote === 'genius').length;
      geniusPercentage = Math.round((geniusVotes / cumulativeVotes.length) * 100);
    }

    points.push({
      timestamp: new Date(intervalEnd).toISOString(),
      geniusPercentage,
      velocity
    });
  }

  return points;
});

// POST /api/log - Receives client-side browser logs and prints them to server stdout
fastify.post('/api/log', async (request, reply) => {
  console.log(`[CLIENT-SIDE] [${request.body.type.toUpperCase()}] ${request.body.message}`);
  return { ok: true };
});

// POST /api/generate-post - Generates a viral social media post using Gemini
fastify.post('/api/generate-post', async (request, reply) => {
  const { trendTitle, platform, contextType } = request.body || {};
  if (!trendTitle) {
    return reply.status(400).send({ error: 'Trend title is required.' });
  }
  const targetPlatform = platform || 'x';
  const targetContext = contextType || 'general';

  const slug = titleToSlug(trendTitle);
  const targetUrl = `https://viraljacker.com/t/${slug}`;

  if (process.env.NODE_ENV === 'test' || !genAI) {
    let postText = '';
    if (targetPlatform === 'x' || targetPlatform === 'twitter') {
      postText = `Breaking: ${trendTitle} is trending! Angle: ${targetContext}. Check out: ${targetUrl} #${trendTitle.replace(/\s+/g, '')} #Tech`;
      if (postText.length > 280) {
        postText = postText.substring(0, 277) + '...';
      }
    } else if (targetPlatform === 'linkedin') {
      postText = `Exciting update on ${trendTitle}!\n\nWe are seeing major interest in this topic with angle: ${targetContext}.\nRead full analysis here: ${targetUrl}\n\n#AI #Innovation #Technology`;
    } else if (targetPlatform === 'facebook') {
      postText = `What do you think about ${trendTitle}? It's viral right now under ${targetContext}. Read here: ${targetUrl} #${trendTitle.replace(/\s+/g, '')} #Viral`;
    } else if (targetPlatform === 'reddit') {
      postText = `Why is ${trendTitle} trending? (${targetContext})\n\nHere is a quick summary of the trend. Check out the full breakdown and vote here: ${targetUrl}`;
    } else {
      postText = `Mock post for ${targetPlatform} with context ${targetContext} about ${trendTitle}!\n${targetUrl}`;
    }
    return { postText };
  }

  try {
    const model = genAI.getGenerativeModel({
      model: 'gemini-3.5-flash',
    });

    let platformInstructions = '';
    if (targetPlatform === 'x' || targetPlatform === 'twitter') {
      platformInstructions = `
- Platform: X (Twitter).
- Length constraint: The entire post must be strictly under 280 characters, including the target URL.
- Hashtags: Include 2 to 3 highly relevant, hyper-targeted hashtags (e.g., #CricketTwitter, #AIAgents) based on the trend topic.`;
    } else if (targetPlatform === 'linkedin') {
      platformInstructions = `
- Platform: LinkedIn.
- Style: Professional, engaging.
- Hashtags: Include exactly 3 professional, structured hashtags on the very last line of the post (e.g., #AI #Innovation #Technology).`;
    } else if (targetPlatform === 'facebook') {
      platformInstructions = `
- Platform: Facebook.
- Style: Broadly appealing, clean.
- Hashtags: Include exactly 1 to 2 generic, relevant hashtags.`;
    } else if (targetPlatform === 'reddit') {
      platformInstructions = `
- Platform: Reddit.
- Style: Reddit formatting. Do NOT include any hashtags. Frame the post with a catchy title/headline as the first line, followed by a double newline and a brief structured summary/body.`;
    } else {
      platformInstructions = `- Platform: ${targetPlatform}`;
    }

    const prompt = `You are a world-class viral social media marketer. Generate a highly engaging, professional yet catchy social media post about the trending topic "${trendTitle}".

The angle/context for the post is: "${targetContext}".
You MUST explicitly include the following target URL in the post: "${targetUrl}"

Platform-Specific Constraints:
${platformInstructions}

Tone & Style Rules:
- Output ONLY the final post content. No meta-commentary, no introductory sentences ("Here is your post:"), no wrapping quotes around the entire post.
- Use a concise, human-sounding, active tone. Start with a compelling hook or curiosity-inducing question.
- Avoid generic AI transitions/jargon (e.g., "In a surprising turn of events", "Furthermore", "Delve into", "Unlock", "In conclusion", "Embark", "Revolutionize").
- Use clean spacing and strategic emojis where appropriate to match high-quality human styling.`;

    const result = await model.generateContent(prompt);
    const postText = result.response.text().trim();
    return { postText };
  } catch (err) {
    fastify.log.error(err);
    return reply.status(500).send({ error: 'Failed to generate post.' });
  }
});

// Start the Fastify server
const port = process.env.PORT || 3000;
fastify.listen({ port, host: '0.0.0.0' }, async (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  console.log(`Trend-Jacker PoC running at http://localhost:${port}`);
  
  // Initialize trends cache
  if (process.env.NODE_ENV === 'test') {
    latestTrends = [
      {
        id: 1,
        title: "Google Gemini",
        traffic: "100K+",
        description: "The latest AI models from Google.",
        source: "google",
        news: {
          headline: "Google announces Gemini 3.5",
          snippet: "Gemini 3.5 is now live with advanced reasoning capabilities.",
          url: "https://blog.google/gemini-3.5",
          source: "Google Blog",
          ogImage: "https://blog.google/static/images/gemini-hero.png",
          favicon: "https://blog.google/favicon.ico"
        }
      },
      {
        id: 2,
        title: "Fastify framework",
        traffic: "20K+",
        description: "High performance web framework for Node.js.",
        source: "google",
        news: {
          headline: "Fastify v5 released",
          snippet: "Fastify v5 introduces improved plugin loading and security features.",
          url: "https://fastify.io/v5-release",
          source: "Fastify Blog",
          ogImage: null,
          favicon: "https://www.google.com/s2/favicons?domain=fastify.io&sz=32"
        }
      },
      {
        id: 3,
        title: "Reddit Spike Topic",
        traffic: "Reddit Spike",
        description: "Hot post on r/technology",
        source: "reddit",
        news: {
          headline: "Reddit Spike Topic: OpenAI leaks new model features",
          snippet: "A viral post in r/technology outlines upcoming features.",
          url: "https://www.reddit.com/r/technology/comments/1u1ngzk/openai_leaks_new_model_features",
          source: "r/technology",
          ogImage: null,
          favicon: "https://www.google.com/s2/favicons?domain=www.reddit.com&sz=32"
        }
      }
    ];
    console.log("Running in test mode. Populated cache with mock trends.");
  } else {
    await updateTrendsCache();
    // Refresh cache every 10 minutes
    setInterval(updateTrendsCache, 10 * 60 * 1000);
  }

  // Seed recentActivityLog queue on startup
  seedRecentActivityLog();

  // Verification step
  if (recentActivityLog.length === 10) {
    console.log(`Verification: recentActivityLog seeded successfully with ${recentActivityLog.length} items.`);
  } else {
    console.error(`Verification: Failed to seed recentActivityLog queue properly. Size is ${recentActivityLog.length}`);
  }
});
